### ISSUE TITLE
Use baseUrl instead of hardcoding port into specs

### ISSUE THREAD

**Issue by cblgh** [cypress-io/cypress-example-kitchensink#134]
:wave: 

i'm doing research on frontend testing for the company i work for and i came across Cypress. 

i tried to run the kitchen sink testing suite to see it in action, but since it relies on port `8080` being free it broke due to a pre-existing webserver.

as a first-timer to the project i was uncertain if there was a port i could set anywhere to have it listen to another webserver, but after some digging it turns out you've just hardcoded the request URLs in the specs. 

my suggestion would be
*  **remove** the hardcoded paths in the specs
* **set** `  "baseUrl": "http://127.0.0.1:8080/"` in `cypress.json`
* **add** a note to this project's readme that `baseUrl` should match the url from `npm run start`'s output 
```
Starting up http-server, serving app
Available on:
  http://127.0.0.1:8080    <--- (this was http://127.0.0.1:8083 in my case)
```
~cblgh

**Comment by cblgh** [comment]
i went ahead and made a pr https://github.com/cypress-io/cypress-example-kitchensink/pull/135 with the suggestions above, feel free to do close/merge/whatever!

**Comment by jennifer-shehane** [comment]
@cblgh Thanks for the suggestion! This isn't the first time we have gotten it. 

**This repo serves 2 purposes which makes this change a little bit more work.**
1. It's a great repo to fork and get running yourself to play around with (as you have done).
2. It serves as the scaffolding for the `example` project that Cypress seeds in every new project. 

The suggestion you made works great for #1, but requires some changes to accommodate #2. 

For #2, we do not include a `cypress.json` file in new projects. We also replace all of the urls with `https://example.cypress.io` so that they don't require any server to be running, so just including the baseUrl in the `cypress.json` file is not a solution. 

We do already [have a script](https://github.com/cypress-io/cypress/blob/develop/packages/example/bin/convert.js#L11) written that transforms the `localhost` url to `example.cypress.io` url, so it is likely possible that we could also update the script to handle the url's missing the `localhost` url (since it's included in the `cypress.json`).

**Comment by cblgh** [comment]
alright, in that case i'll go ahead and close it :)
