### ISSUE TITLE
how to select db by cypress

### ISSUE THREAD

**Issue by ycwdaaaa** [cypress-io/cypress-example-kitchensink#433]
In my cases I need to select from mysql to check some task status or I need to change the status by update the db. So how can I do it ?

**Comment by ycwdaaaa** [comment]
I try to use mysqljs/mysql  but got the Net.createConnection is not a function error

**Comment by jennifer-shehane** [comment]
Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.
