### ISSUE TITLE
Spec file names

### ISSUE THREAD

**Issue by ghost** [cypress-io/cypress-example-kitchensink#449]
Any thoughts on best practice for spec file names as I have seen them named two ways:

1. File name suffixed with "_spec.js"
2. File name suffixed with ".spec.js"
3. Really doesn't matter

Any preferences: 1, 2 or 3

**Comment by pedrohyvo** [comment]
In my opinion, the option 2 is the best way to write spec file names.

**Comment by jennifer-shehane** [comment]
Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.
