### ISSUE TITLE
Fix the gitlab ci

### ISSUE THREAD

**Issue by jg-cantaa** [cypress-io/cypress-example-kitchensink#573]
The Gitlab CI is failing for the kitchensink.
Logs for the failure can be seen here:
https://gitlab.com/cypress-io/cypress-example-kitchensink/-/jobs/3220209059

![image](https://user-images.githubusercontent.com/95756912/199251219-3d97ace9-7ca3-40d5-8163-68fe8bc660aa.png)

In a private repo, forked off the kitchensink, the CI fails with the same error.

**Comment by lmiller1990** [comment]
Looks like the wrong version of Node - we will need to update to Node 14.

**Comment by MikeMcC399** [comment]
@lmiller1990 

> Looks like the wrong version of Node - we will need to update to Node 14.

I wonder why you suggest Node.js 14 rather than the LTS version Node.js 18.

The last commit on https://gitlab.com/cypress-io/cypress-example-kitchensink/-/commits/master is from Dec 7, 2022, so the repo is out of date in any case and not synced with this repo. Is that supposed to happen automatically or is it somebody's responsibility to sync it manually from time to time?

**Comment by lmiller1990** [comment]
I think I wrote Node.js 14 since that's when that syntax was first supported. We can definitely update to Node.js 18, though. I don't think there's a specific person or team responsible for this particular task or repo (small team, hundreds of examples and repos to maintain and update).

**Comment by MikeMcC399** [comment]
@lmiller1990 

- I have submitted https://github.com/cypress-io/cypress-example-kitchensink/pull/614 to update several examples, including the GitLab example.

**Comment by lmiller1990** [comment]
It looks like #615 is not happening (the sync). Instead, we will archive it.

Any benefit to keeping this open? Looks like #615 captures the remaining work.

**Comment by emilyrohrbough** [comment]
@lmiller1990 No we can close.
