### ISSUE TITLE
Timeout failure for getComment aliases when all the tests are run

### ISSUE THREAD

**Issue by katnem** [cypress-io/cypress-example-kitchensink#86]
There are several getComment aliases in the tests (network_requests.spec.js, waiting.spec.js and files.spec.js). Whenever the mentioned tests are run individually, they pass. Whenever all the tests are run together, the mentioned tests fail with the following error: "Timed out retrying: cy.wait() timed out waiting 5000ms for the 1st request to the route: 'getComment'. No request ever occurred."

**Comment by jennifer-shehane** [comment]
Yes, this is happening when clicking 'run all tests' and having all specs run tests together. 

I am not encountering this error when running the tests that are seeded in the Cypress project itself (added when you create a new project) - which are using the Kitchen-Sink version 1.0.1. This makes me believe that this bug was introduced in one of the commits on this project after May 14, 2018 https://github.com/cypress-io/cypress-example-kitchensink/commits/master

I'm quite confused why our automated tests would not have caught this though. 

Can you confirm that you forked the repository and ran it on your own?

Cy Version: 3.0.1
Browser: Chrome 67 / Electron 59
OS: Mac

**Comment by jennifer-shehane** [comment]
Oh, well, duh, they weren't caught because the specs are run in isolation within CI, not as if you had clicked 'run all tests'

**Comment by jennifer-shehane** [comment]
I was able to narrow down the bug to these lines of code:

```js
beforeEach(() => {
  cy.visit('http://localhost:8080/commands/files')
})

it('.defaults() - change default config of server', () => {
  Cypress.Server.defaults({
    whitelist (xhr) {
      expect(xhr).to.be.an('object')
    },
  })
})

it('cy.fixture() - load a fixture', () => {
  cy.server()
  cy.route('GET', 'comments/*').as('getComment')
  cy.get('.fixture-btn').click()
  cy.wait('@getComment')
})
```

**Comment by jennifer-shehane** [comment]
The assertion below is failing, but failing in a later test - while trying to process the `.wait()` command.

```
expect(xhr).to.be.an('object')
```

![screen shot 2018-06-28 at 1 01 20 pm](https://user-images.githubusercontent.com/1271364/42049275-7ec10a14-7ad3-11e8-9224-ffc514f03358.png)

**Comment by jennifer-shehane** [comment]
Ok, so we are going to remove the `whitelist` sections of the `Cypress.Server.default({})`. 

This isn't really a good use case of how the whitelist feature should be used - ideally you would rewrite the function and not add an arbitrary assertion in here. Because of the way error handling is handled in this case, the error is being pushed off and being thrown on the `.wait()` command. Which is why all of these waits are failing. 

There does not appear to be an error in Cypress itself that we should open an issue for.

**Comment by katnem** [comment]
Thanks  @jennifer-shehane =)
